### PR TITLE
fix: issue #13

### LINKED ISSUE #13: Issue with Products Link in the footer
Right Now, using the products link in the footer to navigate on the Products page adds nothing in the URL for the search params

https://user-images.githubusercontent.com/56081584/159474296-a4cc187c-207a-49dc-8b8b-dc1fbbc37347.mp4

And, if we are already on the Products page and have selected some filters then clicking on the products link in the footer is removing the already selected filter data from the URL, but don't remove the selected filters.

https://user-images.githubusercontent.com/56081584/159475115-3a89a971-05de-430a-9019-bf591d69b4e0.mp4

This is a bug, if there are some filters that are selected then it should not remove their properties from the URL, in this way we can't share the URL with others.

### PR DESCRIPTION
**Pull request by hsnice16**
This PR solves issue #13

### CODE REVIEW

File: src/App.js [hunk 1]
```diff
@@ -38,7 +39,7 @@ function App() {
       )}
 
       <Routes>
-        <Route path="/" element={<Home />} />
+        <Route path={ROUTE_ROOT} element={<Home />} />
```
Comment (arjun-computer-geek) [inline src/App.js:42]: This is not good way of using constant. It is more confusing. It decrease the code readability.

**Review by arjun-computer-geek — APPROVED** [review]
else look good.

File: src/App.js (hunk 1 above)
Comment (hsnice16) [reply src/App.js:42]: I think it does not decrease the code readability, as we can easily refer what are the routes that are present in an app through their route constant file.

And using constants for routes make it easy to do changes in route. Suppose right now the route for home page is `/home`, and after some time I want to change it into `/app/home`, if I will not maintain a single source of truth for the routes then, I have to check all the pages, all the components where I am using the route `/home` and then have to make changes their.

By using a constant, I can easily do the changes at only one place and it will be changed everywhere I am using the respective constant.

Using variable for the route `/` may not be obvious because we usually not use it at many place and also we do not change it. But I want to keep consistency, so that's why I used.

Comment (hsnice16) [reply src/App.js:42]: Thanks for sharing your thoughts. And if you can refer to some blog which says this way is not good then it would be nice. I would definitely give it a read.

Comment (arjun-computer-geek) [reply src/App.js:42]: Ok I got your thoughts.

**Review by Ronak-Mutha — APPROVED** [review]
Good use of constants and utilities. Good to merge.

**Comment by hsnice16** [comment]
Thank you for reviewing,
